name: publish

on: [push]

jobs:
  publish-hello-world-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: login ghcr.io
      run: |
        echo $CR_PAT | docker login ghcr.io -u ionutgaina --password-stdin
      env:
        CR_PAT: ${{ secrets.CR_PAT }}

    - name: build image and push to ghcr.io
      run: |
        docker build . --tag ghcr.io/ionutgaina/test-ghcr:latest
        docker run ghcr.io/ionutgaina/test-ghcr:latest
        docker push ghcr.io/ionutgaina/test-ghcr:latest
